#! /bin/sh

# Written using Git 1.7.2.3, may work with older
#
# Recommend running like
#    TMPDIR=/dev/shm ./git-importing/cvs2git-intcvs1-foo anacode


PROJ=${1:-foo}
IEC_NAME=$PROJ

GIDIR=$(
    cd $( dirname $0 )
    echo $PWD
)
export PATH=$GIDIR:$PATH

# Import functions
source $GIDIR/cvs2git-funcs

unpack_hwime ~/tmp/$PROJ.repo.tgz || fetchrepo
canon_repocvs CVSREPO-$( echo $PROJ | tr a-z A-Z )
subdir_promote

unpack_hwime ~/tmp/$PROJ.git.tgz  || do_import

checktags_all

clean_git_namespace
clean_git_workingcopy

checktag_show_summary
